
target-y = \
	mbus-command

mbus-command_includes-y = \
	../../dist/include

mbus-command_libraries-y = \
	../../dist/lib

mbus-command_files-y = \
	command.c

mbus-command_ldflags-y = \
	-lmbus-debug \
	-lmbus-client \
	-lmbus-json

distdir = ../../dist

dist.bin-y = \
	mbus-command

include ../../Makefile.lib
