
target-y = \
	mbus-cli

mbus-cli_includes-y = \
	../../dist/include

mbus-cli_libraries-y = \
	../../dist/lib

mbus-cli_files-y = \
	cli.c

mbus-cli_ldflags-y = \
	-lmbus-debug \
	-lmbus-client \
	-lmbus-json

distdir = ../../dist

dist.bin-y = \
	mbus-cli

include ../../Makefile.lib
