
target.so-y = \
	libmbus-exec.so

libmbus-exec.so_includes-y = \
	../../dist/include

libmbus-exec.so_libraries-y = \
	../../dist/lib

libmbus-exec.so_files-y = \
	exec.c

libmbus-exec.so_ldflags-y = \
	-lmbus-debug

distdir = ../../dist

dist.include-y = \
	exec.h

dist.lib-y = \
	libmbus-exec.so

include ../../Makefile.lib
