
target-y = \
	mbus-event

mbus-event_includes-y = \
	../../dist/include

mbus-event_libraries-y = \
	../../dist/lib

mbus-event_files-y = \
	event.c

mbus-event_ldflags-y = \
	-lmbus-debug \
	-lmbus-client \
	-lmbus-json

distdir = ../../dist

dist.bin-y = \
	mbus-event

include ../../Makefile.lib
