
target.so-y = \
	libmbus-json-cJSON.so

libmbus-json-cJSON.so_files-y = \
	cJSON.c

libmbus-json-cJSON.so_ldflags-y = \
	-lm

distdir = ../../../dist

dist.base = mbus

dist.lib-y = \
	libmbus-json-cJSON.so

include ../../../Makefile.lib
