
target.so-y = \
	libmbus-cJSON.so

libmbus-cJSON.so_files-y = \
	cJSON.c

libmbus-cJSON.so_ldflags-y = \
	-lm

distdir = ../dist

dist.base = mbus

dist.include-y = \
	cJSON.h

dist.lib-y = \
	libmbus-cJSON.so

include ../Makefile.lib
