
target.so-y = \
	libmbus-socket.so

libmbus-socket.so_includes-y = \
	../../dist/include

libmbus-socket.so_libraries-y = \
	../../dist/lib

libmbus-socket.so_files-y = \
	socket.c

libmbus-socket.so_ldflags-y = \
	-lmbus-debug

distdir = ../../dist

dist.include-y = \
	socket.h

dist.lib-y = \
	libmbus-socket.so

include ../../Makefile.lib
