
subdir-y = \
	debug \
	buffer \
	client \
	clock \
	compress \
	json \
	method \
	server \
	socket \
	queue \
	version

buffer_depends-y = \
	debug \
	compress

client_depends-y = \
	debug \
	buffer \
	json \
	method \
	socket \
	server \
	version

clock_depends-y = \
	debug

compress_depends-y = \
	debug

method_depends-y = \
	debug

server_depends-y = \
	debug \
	buffer \
	clock \
	compress \
	json \
	method \
	socket \
	queue \
	version

socket_depends-y = \
	debug

include ../Makefile.lib
