
subdir-y = \
	debug \
	buffer \
	client \
	clock \
	compress \
	json \
	method \
	server \
	socket \
	queue

buffer_depends-y = \
	debug \
	compress

client_depends-y = \
	debug \
	buffer \
	json \
	method \
	socket \
	server

clock_depends-y = \
	debug

compress_depends-y = \
	debug

method_depends-y = \
	debug

server_depends-y = \
	debug \
	buffer \
	clock \
	compress \
	json \
	method \
	socket \
	queue

socket_depends-y = \
	debug

include ../Makefile.lib
