
subdir-y = \
	debug \
	buffer \
	client \
	clock \
	exec \
	json \
	method \
	server \
	socket \
	queue

buffer_depends-y = \
	debug

client_depends-y = \
	debug \
	buffer \
	json \
	method \
	socket \
	server

clock_depends-y = \
	debug

exec_depends-y = \
	debug

method_depends-y = \
	debug

server_depends-y = \
	debug \
	buffer \
	clock \
	json \
	method \
	socket \
	queue

socket_depends-y = \
	debug

include ../Makefile.lib
