
target-y = \
	mbus-launcher

mbus-launcher_includes-y = \
	../../dist/include

mbus-launcher_libraries-y = \
	../../dist/lib

mbus-launcher_files-y = \
	launcher.c

mbus-launcher_ldflags-y = \
	-lmbus-debug \
	-lmbus-cJSON \
	-lmbus-exec

distdir = ../../dist

dist.bin-y = \
	mbus-launcher

include ../../Makefile.lib
