
target-y = \
	mbus-version

mbus-version_includes-y = \
	../../dist/include

mbus-version_libraries-y = \
	../../dist/lib

mbus-version_files-y = \
	version.c

mbus-version_ldflags-y = \
	-lmbus-version

distdir = ../../dist

dist.bin-y = \
	mbus-version

include ../../Makefile.lib
